### ISSUE TITLE
Duration example？

### ISSUE THREAD

**Issue by WhiteFu** [ivanvovk/DurIAN#1]

**Comment by WhiteFu** [comment]
Could you provide a example of the phonemized and duration-aligned dataset? I don't really understand the process of duration-algin.

**Comment by ivanvovk** [comment]
Do you mean just the example of dataset or aligning process description? For dataset example look up to the `filelists` folder, where I uploaded aligned LJSpeech dataset. For single item entities are splited with "|" character and are as follows: text, phonemes start, phonemes duration, phonemes, filename.

**Comment by WhiteFu** [comment]
> Do you mean just the example of dataset or aligning process description? For dataset example look up to the `filelists` folder, where I uploaded aligned LJSpeech dataset. For single item entities are splited with "|" character and are as follows: text, phonemes start, phonemes duration, phonemes, filename.

Thanks for your reply,  I am a beginner. So I want to know the parsing process of the duration-aligned dataset in this repo.  I want to apply it to the other dataset.  If you don't mind,  Could you provide a tutorial in this repo in the future?

**Comment by ivanvovk** [comment]
Sure. I have some free time in the nearest future, so I will provide some guidances.

**Comment by ivanvovk** [comment]
I have just added to README the approximate algorithm for alignment process of your own data based on Montreal Forced Aligner tool. I guess this is the best and the quickest approach for dataset alignment right now. It is quite accurate and simple in use. Have a look, hope it will help you.
P.S. Try it just on several data points firstly, not on the whole dataset to ensure you have done everything right.

**Comment by WhiteFu** [comment]
Good Job, thanks a lot!

**Comment by ivanvovk** [comment]
You're welcome! Closing this issue.
